package books.util;

public enum Campos {
    BookId,
    Title,
    Author,
    AuthorLf,
    AdditionalAuthors,
    ISBN,
    ISBN13,
    MyRating,
    AverageRating,
    Publisher,
    Binding,
    Pages,
    YearPublished,
    OriginalPublicationYear,
    DateRead,
    DateAdded,
    Bookshelves,
    BookshelvesWithPositions,
    ExclusiveShelf,
    MyReview,
    Spoiler,
    PrivateNotes,
    ReadCount,
    RecommendedFor,
    RecommendedBy,
    OwnedCopies,
    OriginalPurchaseDate,
    OriginalPurchaseLocation,
    Condition,
    ConditionDescription,
    BCID
}